# vim:syntax=ruby:

tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'entr'
brew 'fd'
brew 'fish'
brew 'git'
brew 'git-lfs'
brew 'gron'
brew 'jq'
brew 'ripgrep'
brew 'tree'
brew 'tree-sitter'
brew 'xz'

cask 'firefox'
cask 'font-iosevka'
cask 'kitty', args: { 'no-quarantine': true }
cask 'rectangle'
cask 'skype'
cask 'spotify'
cask 'transmission'
cask 'visual-studio-code'
