# vim:syntax=ruby:

tap 'homebrew/cask'

brew 'entr'
brew 'fd'
brew 'fish'
brew 'git'
brew 'git-lfs'
brew 'gron'
brew 'jq'
brew 'ripgrep'
brew 'tree'
brew 'ttfautohint'
brew 'xz'

cask 'firefox'
cask 'godot'
cask 'kitty', args: { 'no-quarantine': true }
cask 'rectangle'
cask 'skype'
cask 'spotify'
