#!/usr/bin/env bash

source "$HOME/.config/bash/gruvbox_256palette_osx.sh"

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# show command return value if not successful or ctrl-c
nonzero_return () {
    RET=$?
    { [ $RET -ne 0 ] && [ $RET -ne 130 ]; } && echo "[$RET] "
}
export PS1="\[\e[93m\]\`nonzero_return\`\[\e[91m\]\W λ\[\e[m\] "

export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
HISTSIZE=-1
HISTFILESIZE=-1
HISTCONTROL=ignoreboth:erasedups
HISTIGNORE='ls:ls -lash:exit'
shopt -s histappend cmdhist

history_dedupe () {
    awk '{$1=$1};1' "$HOME/.bash_history" | nl | sort -k2 -rk1 | uniq -f1 | sort -k1 | cut -f 2 > ~/.bash_history_uniq
    mv ~/.bash_history_uniq ~/.bash_history
}
trap history_dedupe EXIT


export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"

export HOMEBREW_BUNDLE_FILE="$HOME/.config/homebrew/Brewfile"
export HOMEBREW_BUNDLE_NO_LOCK=true

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

[ -f "$HOME/.fzf.bash" ] && source "$HOME/.fzf.bash"
[ -r "$HOME/.opam/opam-init/init.sh" ] && { source "$HOME/.opam/opam-init/init.sh" > /dev/null 2> /dev/null || true; }
